Algoritmo "ProcedimentoComParametroMulti"
procedimento multi(x,y:inteiro)
var
aux: inteiro
inicio
aux <- x * y
resposta <- aux
fimprocedimento

Var
// Seção de Declarações das variáveis

resposta, n, m: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
// Sinal de atribuição "<-", quando uma variável recebe um valor
n <- 156
m <- -14

multi(n,m)

Escreval(resposta)

Fimalgoritmo