Algoritmo "ProcedimentoComParametroSoma"
procedimento soma(x,y:inteiro)
var
aux: inteiro
inicio
aux <- x + y
resposta <- aux
fimprocedimento

Var
// Seção de Declarações das variáveis

resposta, n, m: inteiro


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
// Sinal de atribuição "<-", quando uma variável recebe um valor
n <- 4
m <- -9

soma(n,m)

Escreval(resposta)

Fimalgoritmo