Algoritmo "RepeticaoEnquanto"


Var
// Seção de Declarações das variáveis
nomeAlg: caracter
i,j: inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
// Sinal de atribuição "<-", quando uma variável recebe um valor
nomeAlg <- "Repetição Enquanto"
Escreval("Nome do Algoritmo: ", nomeAlg)

i <- 1
Enquanto i <= 10 faça
Escreval("Valor de i: ", i)
i <- i + 1
fimEnquanto


Fimalgoritmo