Algoritmo "RepeticaoPara"


Var
// Seção de Declarações das variáveis
nomeAlg: caracter
i,j: inteiro



Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
// Sinal de atribuição "<-", quando uma variável recebe um valor
nomeAlg <- "Repetição Para"
Escreval("Nome do Algoritmo: ", nomeAlg)

Para i de 1 até 10 faça
Escreval ("Valor de i: ", i)
         Para j de 1 até 3 faça
         Escreval ("j: ", j)
         FimPara
FimPara

Fimalgoritmo